/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameControl from "./control/GameControl"
import stick from "./control/stick"
import enemy from "./object/enemy"
import player from "./object/player"
import star from "./object/star"
import wall from "./object/wall"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=667;
    static height:number=375;
    static scaleMode:string="fixedwidth";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="battle.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("control/GameControl.ts",GameControl);
        reg("control/stick.ts",stick);
        reg("object/enemy.ts",enemy);
        reg("object/player.ts",player);
        reg("object/star.ts",star);
        reg("object/wall.ts",wall);
    }
}
GameConfig.init();